// MCP mode for the vibepin daemon (opt-in; requires @modelcontextprotocol/sdk).
// Exposes three tools over Streamable HTTP at /mcp:
//   - list_annotations    : current pending annotations (no drain)
//   - watch_annotations   : long-poll; blocks until new annotations arrive (the watch-mode loop)
//   - resolve_annotation  : settle the batch ledger + archive the claim
//
// Mirrors vibe-annotations' watch_annotations loop, but the overlay it feeds is
// universal (web + Electron + pixel capture), not a Chrome extension.
//
// Session routing (§8.2). Each tool takes an optional `sessionId`:
//   with sessionId    -> read that session's queue *and* the shared inbox; a
//                        resolve settles the ledger, then appends to claims.jsonl
//                        (no queue rewrite)
//   without sessionId -> shared inbox only, byte-for-byte today's behaviour
//
// The routing key can only come from a *tool argument*. The transport-level
// `mcp-session-id` is generated by randomUUID() per connection, lives in memory,
// and is dropped on close or daemon restart — a route bound to it would silently
// stop resolving, so it is never treated as a session identity (design §13 ④).

import { randomUUID } from 'node:crypto';
import { ackByIds } from './batches.js';

// The SDK is imported lazily, for two reasons: the daemon still runs in plain
// file mode with no node_modules, and the routing surface below stays testable
// without the SDK installed. `buildServer` only attaches zod schemas to it.
async function loadSdk() {
  const [mcp, http, types, zod] = await Promise.all([
    import('@modelcontextprotocol/sdk/server/mcp.js'),
    import('@modelcontextprotocol/sdk/server/streamableHttp.js'),
    import('@modelcontextprotocol/sdk/types.js'),
    import('zod'),
  ]);
  return {
    McpServer: mcp.McpServer,
    StreamableHTTPServerTransport: http.StreamableHTTPServerTransport,
    isInitializeRequest: types.isInitializeRequest,
    z: zod.z ?? zod,
  };
}

// The session id shape from design §4.1, quoted back in errors so a client can
// see why its value was refused. The authoritative check is `sessions.valid`.
const SID_SHAPE = 'a short id like "omp-2f9c1a" (^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$)';

export function createToolBindings(store, sessions) {
  // A session's read set: its own queue first, then the shared inbox — the same
  // semantics as the file path (`watch --queue` + `--inbox`), so both a targeted
  // note and a broadcast note reach it, and neither one can be seen by a session
  // it was not addressed to.
  const filesFor = (sid) => (sid ? [sessions.queuePath(sid), store.INBOX] : [store.INBOX]);

  // Every tool call carrying a sessionId is a heartbeat: the daemon upserts the
  // lease (mode "mcp"). An MCP client has no process of its own to write one
  // (Antigravity) and no way to send an HTTP heartbeat from a tool (Codex's shell
  // is network-sandboxed, §6.1), so server-side upsert is the only option that
  // holds. A tool call is also the freshest signal we have that the session is
  // alive — hence `lastReArmAt` on every call.
  function touch(sid) {
    // The patch is a function of the record on disk, so a lease that watch.js
    // created keeps its label / cwd / lastClaimAt while the MCP layer stamps it
    // as `mode: "mcp"` (store.writeLease replaces, rather than merges, when the
    // patch is a function — hence the spread).
    return sessions.writeLease(sid, (prev) => ({
      ...prev,
      agent: typeof prev.agent === 'string' && prev.agent ? prev.agent : 'mcp',
      mode: 'mcp',
      lastReArmAt: Date.now(),
    }));
  }

  // §4.1: an invalid sid is an error, never a path. Checked before any disk use,
  // and an empty/absent value simply means "no target" (broadcast read set).
  function requireValid(sessionId) {
    if (sessionId === undefined || sessionId === null || sessionId === '') return null;
    if (!sessions.valid(sessionId)) throw new Error(`bad sessionId: ${JSON.stringify(sessionId)} — expected ${SID_SHAPE}`);
    return sessionId;
  }

  return {
    async list({ sessionId } = {}) {
      const sid = requireValid(sessionId);
      if (sid) await touch(sid);
      return store.readAll(filesFor(sid));
    },

    async watch({ timeoutMs, sessionId } = {}) {
      const sid = requireValid(sessionId);
      if (sid) await touch(sid);
      // Parked is the most accurate liveness signal available: while this promise
      // is open the session is alive by construction, so /sessions reports
      // lastSeenAt 0 instead of "last activity N minutes ago" (§8.2). Display
      // only — it never decides whether a note is delivered (§1.4 invariant 3).
      if (sid) sessions.markInFlight(sid, true);
      try {
        return await store.waitForAny(filesFor(sid), timeoutMs ?? 25000);
      } finally {
        if (sid) sessions.markInFlight(sid, false);
      }
    },

    async resolve({ ids, sessionId, note } = {}) {
      const sid = requireValid(sessionId);
      if (sid) await touch(sid);
      // Settle the ledger. `vibepin report` reads the ledger's item status, so
      // without this an MCP-resolved note stays `open` for ever and its report
      // never reaches exit 0 — the comparison table the user checks against lies.
      // `note` is required for that transition (it becomes the 证据 column);
      // `ackItems` enforces it, and throws before anything is written.
      //
      // `owner` is the routing key for the ledger half: only the session that
      // claimed a batch may answer it. It cannot be scoped by "is it still pending
      // in my read set" — by the time an agent resolves, `claim.js` has already
      // drained the queue, so the id is no longer visible while the batch still
      // records whose it is.
      const warnings = [];
      const settled = await ackByIds(store.INBOX, ids, { note, owner: sid ?? null, onWarn: (w) => warnings.push(w) });
      // Append-only (§7.3): resolveByIds adds one claims.jsonl line
      // ({ids, sessionId, at}) and never rewrites a queue, so a concurrent POST
      // cannot be erased by a read-modify-write window.
      const resolved = await store.resolveByIds(ids, filesFor(sid), sid ? { sessionId: sid } : {});
      // The receipt reports a *count*: the old code reported store.size(), i.e.
      // bytes, as if they were annotations (§7.4). "Pending" here means what is
      // still waiting for this caller — its read set, queues and inbox alike.
      // Bucketed so a partial result can never read as complete: `settled` changed,
      // `skipped` was already ruled on (left alone on purpose), `foreign` belongs to
      // another session, `missing` has no ledger item at all (an MCP-only session
      // claims no batch). Together they cover every id asked about.
      const pending = sid
        ? (await store.count(store.queuePath(sid))) + (await store.count(store.INBOX))
        : await store.count(store.INBOX);
      return {
        resolved,
        pending,
        settled: settled.settled,
        skipped: settled.skipped,
        foreign: settled.foreign,
        missing: settled.missing,
        ...(warnings.length ? { warnings } : {}),
      };
    },
  };
}

async function buildServer(store, sessions) {
  const { McpServer, z } = await loadSdk();
  const server = new McpServer({ name: 'vibepin', version: '0.1.0' });
  const tools = createToolBindings(store, sessions);

  // Every tool body returns JSON as one text block, and a refused sessionId comes
  // back as an error result rather than a thrown handler crash — the client sees
  // a sentence it can act on.
  const text = (fn) => async (args) => {
    try {
      return { content: [{ type: 'text', text: JSON.stringify(await fn(args), null, 2) }] };
    } catch (e) {
      return { isError: true, content: [{ type: 'text', text: `Error: ${String(e.message || e)}` }] };
    }
  };
  const sessionId = z.string().optional()
    .describe('Session to route to — the short id from GET /sessions. Omit to read the shared inbox only (older clients).');

  server.tool(
    'list_annotations',
    'List the current pending UI annotations (selector, note, computed styles, optional screenshot). Does not remove anything.',
    { sessionId },
    text((args) => tools.list(args))
  );

  server.tool(
    'watch_annotations',
    'Watch-mode loop: blocks until new UI annotations arrive, then returns them. Returns [] on timeout — call again to keep watching. After implementing each one, call resolve_annotation with its id.',
    { timeoutMs: z.number().int().positive().optional(), sessionId },
    text((args) => tools.watch(args))
  );

  server.tool(
    'resolve_annotation',
    'Mark annotation(s) as done: settles them in the batch ledger (which `vibepin report` reads) and records the claim so they are not delivered again. `note` is required for any id that belongs to a batch — it becomes the 证据 column the user checks against.',
    { ids: z.array(z.string()).min(1), sessionId, note: z.string().optional() },
    text((args) => tools.resolve(args))
  );

  return server;
}

export async function createMcpHandler(store, sessions) {
  let sdk;
  try {
    sdk = await loadSdk();
  } catch {
    return null;   // no node_modules: the daemon stays in plain file mode
  }
  const { StreamableHTTPServerTransport, isInitializeRequest } = sdk;
  const transports = Object.create(null);

  async function readJson(req) {
    const chunks = [];
    for await (const c of req) chunks.push(c);
    if (!chunks.length) return undefined;
    return JSON.parse(Buffer.concat(chunks).toString('utf8'));
  }

  return async function handle(req, res) {
    // Transport handle only — never a vibepin session id (§8.2).
    const transportId = req.headers['mcp-session-id'];

    if (req.method === 'POST') {
      const body = await readJson(req);
      let transport = transportId ? transports[transportId] : undefined;

      if (!transport) {
        if (!isInitializeRequest(body)) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32000, message: 'No valid session; send initialize first' } }));
          return;
        }
        transport = new StreamableHTTPServerTransport({
          sessionIdGenerator: () => randomUUID(),
          enableJsonResponse: true, // plain JSON responses (no SSE framing) — simpler + curl-testable
          onsessioninitialized: (sid) => { transports[sid] = transport; },
        });
        transport.onclose = () => { if (transport.sessionId) delete transports[transport.sessionId]; };
        await (await buildServer(store, sessions)).connect(transport);
      }

      return transport.handleRequest(req, res, body);
    }

    if (req.method === 'GET' || req.method === 'DELETE') {
      const transport = transportId ? transports[transportId] : undefined;
      if (!transport) { res.writeHead(400).end('Invalid or missing session ID'); return; }
      return transport.handleRequest(req, res);
    }

    res.writeHead(405).end();
  };
}
